name: translation_package
description: Package that handle the configuration of the translation for your application.
version: 0.0.1
author: OD&B <hello@odandb.com>
repository: https://github.com/odandb/flutter-translate
homepage: https://github.com/odandb/flutter-translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sprintf: ^4.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter